### ISSUE TITLE
You don't have permission to access /phppgadmin on this server.

### ISSUE THREAD

**Issue by stephanlindauer** [jacksoncage/dockerfiles#2]
when i run my docker compose like so:

``` phppgadmin:
  image: jacksoncage/phppgadmin
  ports:
   - "1234:80"
  environment:
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
```

and go to 

```
http://localhost:1234/phppgadmin
```

then i get

```
Forbidden
You don't have permission to access /phppgadmin on this server.
Apache/2.4.10 (Debian) Server at localhost Port 1234
```

**Comment by arymkus** [comment]
@stephanlindauer fixed in #3 , which is waiting to be merged.

**Comment by stephanlindauer** [comment]
nice!

**Comment by stephanlindauer** [comment]
nice!

**Comment by stephanlindauer** [comment]
oops. didnt want to close the ticket. will wait for merge and theb close.

**Comment by arymkus** [comment]
Ok =)

**Comment by arymkus** [comment]
@stephanlindauer BTW, you just van take files from my PR or forked repo.

**Comment by einfallstoll** [comment]
I've just created a fixed fork of @arymkus version for Docker Hub: https://github.com/einfallstoll/docker-phppgadmin / https://hub.docker.com/r/einfallstoll/phppgadmin/

**Comment by stephanlindauer** [comment]
good job @einfallstoll! thx
i will close this ticket after i think @jacksoncage won't get around merging this pr soon. 
maybe we should move on to https://github.com/einfallstoll/docker-phppgadmin
